# Generated by Django 4.2.17 on 2025-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyalWebpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowImage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slideshow_images/')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
